### ISSUE TITLE
[chart] Support for automatic configuration reload when configmap is updated

### ISSUE THREAD

**Issue by hajdukd** [tomkerkhove/promitor#864] opened 2020-01-31 09:23 UTC
### Specification

It's a common practice to introduce a sidecar / job which verifies whether configmap has changed and in case it did - application configuration is refreshed by request post

### API Specification
- **Verb:** POST
- **Path:** /-/reload
- **Reponse Codes:** 200, 404, 5XX
 
Endpoint to reload configuration when application is running.

**Comment by tomkerkhove** [comment] 2020-01-31 10:53
This is a duplicate of https://github.com/tomkerkhove/promitor/issues/573

We don't have plans to support this for runtime configuration since it's all configured at startup.

**Closed** 2020-01-31 12:27 UTC
Labels: triage
