### ISSUE TITLE
Event hub entity metrics are not reported for Event Hub namespace

### ISSUE THREAD

**Issue by sujithms** [tomkerkhove/promitor#1145] opened 2020-07-04 04:09 UTC
Event hub entity metrics are not reported for Event Hub namespace.Similar to service bus queue metrics which was fixed recently, it looks like the event hub entity metrics are not getting reported within a namespace. It only reflects the metrics associated with the namespace on a whole inspite of using filters.

## Expected Behavior
Event hub entity metrics to be reported too.

## Actual Behavior
Event hub namespace metrics are only getting reported

## Steps to Reproduce the Problem

  1.Installed promitor using helm
  2.Authenticated using Azure credentials.
  3.The pod logs indicate only metrics calculated from EH namespace and not entities within it.

## Configuration
Provide insights in the configuration that you are using:
metrics:
   - name: azure_eh_messages
     description: "EH Incoming mesasges"
     resourceType: Generic
     azureMetricConfiguration:
       metricName: IncomingMessages
       aggregation:
         type: Total
     resources:
     - resourceUri: Microsoft.EventHub/namespaces/eventhub-namespace-name
        filter: EntityName eq 'eh-entity-name'

- Configured scraping schedule: 

<details>
<summary>Used scraping configuration</summary>

```yaml
# Add your scraping configuration here
```
  
</details>

## Specifications

  - Version: latest
  - Platform: ubuntu
  - Subsystem: AKS

**Comment by tomkerkhove** [comment] 2020-07-04 19:03
Thanks for reporting. Can you elaborate on the exact issue that was fixed and what version latest is for you?

**Comment by tomkerkhove** [comment] 2020-07-04 19:09
Also, can you provide the logs of the agent please?

**Comment by sujithms** [comment] 2020-07-04 19:55
The versions used are : 
Helm chart version : 1.6.0
Docker Image version : latest

Similar issue which was reported and fixed related to Service bus is #1050 

As requested, please find the agent logs as below :  

[19:26:55 INF] Starting validation of Promitor setup
[19:26:55 INF] Start Validation step 1/6: Metrics Declaration Path
[19:26:55 INF] Scrape configuration found at '/config/metrics-declaration.yaml'
[19:26:55 INF] Validation step 1/6 succeeded
[19:26:55 INF] Start Validation step 2/6: Azure Authentication
[19:26:55 INF] Validation step 2/6 succeeded
[19:26:55 INF] Start Validation step 3/6: Metrics Declaration
[19:26:55 INF] Metrics declaration is using spec version v1
[19:26:56 INF] Following metrics configuration was configured:
azureMetadata:
  resourceGroupName: xxx-xxx-xxx
  subscriptionId: xxx-xxx-xxx-xxx
  tenantId: xxx-xxx-xxx-xxx
  cloud:
    name: AzureGlobalCloud
    authenticationEndpoint: https://login.microsoftonline.com/
    resourceManagerEndpoint: https://management.azure.com/
    graphEndpoint: https://graph.windows.net/
    managementEndpoint: https://management.core.windows.net/
    storageEndpointSuffix: core.windows.net
    keyVaultSuffix: vault.azure.net
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping: &o0
    schedule: '*/5 * * * *'
metrics:
- azureMetricConfiguration:
    metricName: IncomingRequests
    aggregation:
      type: Total
      interval: 00:05:00
  prometheusMetricDefinition:
    name: azure_eh_requests
    description: EH requests
    labels: {}
  scraping: *o0
  resourceType: Generic
  resources:
  - filter: EntityName eq 'event-hub-name'
    resourceUri: Microsoft.EventHub/namespaces/eventhub-namespace-name
    resourceType: Generic

[19:26:56 INF] Validation step 3/6 succeeded
[19:26:56 INF] Start Validation step 4/6: Resource Discovery
[19:26:56 INF] Validation step 4/6 succeeded
[19:26:56 INF] Start Validation step 5/6: StatsD Metric Sink
[19:26:56 INF] Validation step 5/6 succeeded
[19:26:56 INF] Start Validation step 6/6: Prometheus Scraping Endpoint Metric Sink
[19:26:56 INF] Validation step 6/6 succeeded
[19:26:56 INF] Promitor configuration is valid, we are good to go.
[19:26:56 INF] Metrics declaration is using spec version v1
[19:26:56 INF] [Job][xxx-xxx-xxx-xxx-xxx-azure_eh_requests-Microsoft.EventHub/namespaces/eventhub-namespace-name-xxx-xxx-xxx-xxx-xxx] is running under time zone: Etc/UTC
[19:26:56 INF] Scraping Azure Monitor - 07/04/2020 19:26:56 +00:00
[19:26:56 INF] Scraping azure_eh_requests for resource type Generic
[19:26:56 INF] Now listening on: http://[::]:88
[19:26:56 INF] Application started. Press Ctrl+C to shut down.
[19:26:56 INF] Hosting environment: Production
[19:26:56 INF] Content root path: /app
[19:26:57 INF] Request starting HTTP/1.1 GET http://172.xx.xx.xx:88/api/v1/health
[19:26:57 INF] Request finished in 213.9046ms 200 application/json; charset=utf-8

**Metric exposed :** 

# HELP azure_eh_requests EH requests
# TYPE azure_eh_requests gauge
azure_eh_requests{resource_group="xxx-xxx-xxx",subscription_id="xxx-xxx-xxx-xxx-xxx",resource_uri="subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/xxx-xxx-xxx/providers/Microsoft.EventHub/namespaces/eventhub-namespace-name",instance_name="Microsoft.EventHub/namespaces/eventhub-namespace-name"} 0
# HELP promitor_ratelimit_arm Indication how many calls are still available before Azure Resource Manager is going to throttle us.
# TYPE promitor_ratelimit_arm gauge
promitor_ratelimit_arm{tenant_id="xxx-xxx-xxx-xxx-xxx",subscription_id="xxx-xxx-xxx-xxx-xxx",app_id="xxx-xxx-xxx-xxx-xxx"} 11904

**Comment by sujithms** [comment] 2020-07-04 20:04
As you could notice, it is not reporting the individual Entity metrics within the Event hub namespace which is indeed the expected behavior.

**Comment by tomkerkhove** [comment] 2020-07-04 20:13
Is the metric value correct? I think the resource uri here is correct since that is what is passed, but the filter is not reflected.

Anyhow not ideal but checking the outcome. Would you mind sharing a screenshot of metric explorer in Azure Monitor?

**Comment by sujithms** [comment] 2020-07-04 20:29
Yes the filter seems not to be reflecting correctly.  "EntityName" is the only filter available in metric explorer for Event hub namespaces.

**Comment by tomkerkhove** [comment] 2020-07-05 06:01
Can you share a screenshot of your metric explorer please?

**Comment by sujithms** [comment] 2020-07-05 11:47
As requested here is a snippet of the metrics explorer associated with this metric :

![image](https://user-images.githubusercontent.com/13576074/86531939-4f915680-bee3-11ea-9605-a9054dd029ee.png)

**Comment by tomkerkhove** [comment] 2020-07-05 12:59
Thanks, can you include time and metric aggregation in the screenshot to better understand please?

**Comment by sujithms** [comment] 2020-07-05 13:31
Sure here is the snippet as you requested :  

![image](https://user-images.githubusercontent.com/13576074/86533874-d64d3000-bef1-11ea-853b-017c6fb4f503.png)

This is the doc followed for the metric names : https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported

**Comment by tomkerkhove** [comment] 2020-07-06 07:25
From the looks of it, it looks like it's correctly reporting the metric.

In terms of not using the correct resource URI I'd have to argue that this works by design since that's the ARM resource on which the metrics are exposed and you are filtering out a sub resource.

Now I get that this is not ideal for your metrics, but you can use a custom label to annotate it with the entity name which will be surfaced in the output. By doing this, you can have a metric value per entity.

Here's an example:
```yaml
- name: azure_event_hubs_filtered_with_label
  description: ""
  resourceType: Generic
  labels:
    entityName: topic-1
  azureMetricConfiguration:
    metricName: IncomingMessages
    aggregation:
      type: Total
  resources:
  - resourceUri: Microsoft.EventHub/namespaces/promitor-streaming
    filter: EntityName eq 'topic-1'
```

Hope this helps for you and for what it's worth, an Event Hubs scraper is coming as part of 2.0 which should make this easier for you (#69).

**Comment by sujithms** [comment] 2020-07-06 10:33
Sounds great. All eyes on 2.0 !!!
Yes this seems to report the metric values per entities in EH namespace and can use this definition until the release of 2.0. Thanks for your help !

**Comment by tomkerkhove** [comment] 2020-07-06 11:26
Great to hear and sorry for the slow time-to-resolution!

Ok if we close this one?

**Comment by sujithms** [comment] 2020-07-06 11:31
Yes please go ahead. Thanks !

**Comment by tomkerkhove** [comment] 2020-07-06 11:34
My pleasure! Thanks for using Promitor and happy to [list you as a customer](https://forms.gle/hjcpaaVFa1A1hZaK6) if you are using this in PROD.

**Closed by tomkerkhove** 2020-07-06 11:34 UTC
Labels: support
