### ISSUE TITLE
Promitor should handle or log when rate limit is detected

### ISSUE THREAD

**Issue by jdevalk2** [tomkerkhove/promitor#199] opened 2018-10-22 17:17 UTC
Azure Monitor and more largely Azure Resource Monitor has a feature rate limit, that will limit the amount of requests to 15000 per hour, per ARM instance.

When requesting Azure Monitor you can see the rate limit decrease.

In cases where there are lots of ARM operations going on and Promitor is configured to query lots of resources, potentially it could happen that a rate limit is exceeded.

Therefore users need to be aware that the rate limit exists when configuring, and Promitor should handle the rate limit gracefully possible logging a clear message like "Rate limit exceeded" 

Each ARM response will have a X-Rate-Limit-* or similar HTTP headers and it will list the number of operations that are still possible with ARM. 

I have not looked at the Azure Monitor query API but hopefully they throw this as an exception
If it does then just need to make sure the exception message is clear and that the exceptions would show up outside of Application Insights as well, the channel where Promitor logs its exceptions to at the moment.

**Comment by tomkerkhove** [comment] 2018-10-22 17:28
Thank you @jdevalk2 for the suggestion, it is a fair ask and good feature to add!

I would add that Promitor should expose the current rate limit as a system metric scrapable for Prometheus as well.

**Comment by cnadolny** [comment] 2019-03-28 16:43
Working on this with Vy

**Comment by tomkerkhove** [comment] 2019-03-31 17:24
@cnadolny Just out of curiosity - Did you manage to fix this? If not, what progress did you make and found any relevant docs?

If you prefer not to work on this anymore, no problem - Just let me know, please!

**Comment by cnadolny** [comment] 2019-04-01 02:37
@tomkerkhove I have managed to fix this! Will have a PR out shortly :)

**Comment by tomkerkhove** [comment] 2019-04-01 06:45
Awesome, thanks!

**Comment by tomkerkhove** [comment] 2019-04-02 17:28
@cnadolny is there a particular reason why you've decided to move this to the health endpoint?

I was actually more thinking of moving this to a host variable which will also be available in the Prometheus endpoint via a metric a la PROMITOR_MONITOR_RATELIMIT_SUBSCRIPTION.

Would that make sense? Or do you expect both? What do you think @jdevalk2 @jsturtevant @brusMX?

**Comment by jdevalk2** [comment] 2019-04-02 17:51
Going by this: 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits

I would expose it as a Prometheus Metric like a Gauge, but instead of being an infrastructure metrics, it is an internal metric of Promitor agent itself.

I think next to the rate limit count, you would want to catch and act on HTTP status 429 too many requests. As the rate limit can go from 15K to 0.. However it can fluctuate because of the requests can be routed to multiple ARM datacentres in the same region.

Only when you get a HTTP 429 then for sure you know Promitor can no longer do its job and is in a waiting state.  The actual rate limit count is valuable too, but from a point of you could create an alert rule in Prometheus to trigger when there's only 2000 left for example. So ops would know when to contact Microsoft for an increase or change their configuration.

Health endpoint should just be 200 OK if the agent is up and running. It should not have any additional payload.  

This could be argued: as part of the "Are you healthy?" check you could say if you run out of subscription Reads and are Throttled that could be considered an "Unhealthy" state.

But then you might run into issues with Kubernetes as when the agent is considered unhealthy the pod it's running it would be restarted.  But that would probably turn into a restart loop.

**Comment by tomkerkhove** [comment] 2019-04-02 17:58
That's my concern as well for using the health endpoint and why I want to use Prometheus metric for this.

A gauge is what I had in mind as well, but can you elaborate on this please?

> I would expose it as a Prometheus Metric like a Gauge, but instead of being an infrastructure metrics, it is an internal metric of Promitor agent itself.

To expand on this -
> Only when you get a HTTP 429 then for sure you know Promitor can no longer do its job and is in a waiting state. The actual rate limit count is valuable too, but from a point of you could create an alert rule in Prometheus to trigger when there's only 2000 left for example. So ops would know when to contact Microsoft for an increase or change their configuration.

We'll stop calling Azure Monitor when we are close to hitting the limit, this is tracked in #486.

**Comment by jdevalk2** [comment] 2019-04-02 18:03
> I would expose it as a Prometheus Metric like a Gauge, but instead of being an infrastructure metrics, it is an internal metric of Promitor agent itself.

With the above I meant: Promitor is setup to monitor Azure resources. It exposes these as Prometheus metrics.  So I classify that as one sort of metrics.

Then in addition, Promitor as an agent itself can have metrics as well.  This is another sort of metrics. I said "internal" for this. But it could have any other name.   The metrics concerning the agent itself.

**Comment by tomkerkhove** [comment] 2019-04-02 18:05
So your suggestion would be more to move it to a dedicated scraping endpoint rather than an existing one then, is that a good summary?

@jsturtevant as we've discussed this last week and decided to merge them in one endpoint but after thinking about this again I think a dedicated endpoint would make more sense, no?

Different concerns deserve different endpoints

**Comment by jdevalk2** [comment] 2019-04-02 18:08
If you can have it all (promitor agent status + azure resources) in one metrics endpoint per Promitor agent, from a Prometheus administrative perspective, that is preferred as then you only need to setup 1 service monitor.   

So in general I would try 1 first, until there is really compelling reason to have multiple.

**Comment by tomkerkhove** [comment] 2019-04-02 18:11
We'll use a metric prefix of `PROMITOR_` then.

**Comment by tomkerkhove** [comment] 2019-04-03 09:57
Any input from your side @jsturtevant @brusMX @cnadolny?

**Comment by brusMX** [comment] 2019-04-05 17:09
The health metric was intended in order to be able to see it in a controller while we decided what to do with it and put some logic around it. No real benefit, we started doing it in the last day of the hack so we wanted to iterate quickly on it. 
After our meeting I realized this need to be implemented as a singleton at the application level and we will have to put a logical requirement to all requests to pass this check. We need to implement a “cool off” mechanism and restrict requests to a timely constraint that will not suffocate the endpoint. Gauge does sound better.

**Comment by jdevalk2** [comment] 2019-04-05 17:59
Also with regard to the cool off, I agree there should be logic to hold off calls if they are unlikely to succeed. Also remember the "Retry-After" header in the 429 HTTP response, it literally tells you when it is safe to try again. So until that time has elapsed there would be no point contacting metric endpoint again.

**Comment by tomkerkhove** [comment] 2019-04-06 16:08
That's right, but this is out of scope for this issue.

To summarize:
- Promitor metric will be exposed indicating the current rate limit in metric PROMITOR_MONITOR_RATELIMIT_SUBSCRIPTION.
- Stop calling when reaching x % will be done via #486

**Comment by tomkerkhove** [comment] 2019-05-09 17:51
@jdevalk2 sorry for the delay but this is now available via `promitor_ratelimit_arm`, see [docs](https://promitor.io/operations/#azure-resource-manager-api---consumption--throttling)

This will be available in either v1.0.0 or an earlier preview 1.0.0-preview-6+

**Comment by tomkerkhove** [comment] 2019-05-09 17:51
We'll proactively stop calling ARM via #486

**Closed by tomkerkhove** 2019-05-09 17:51 UTC
Labels: feature-request, operations, specs-required, stability
