### ISSUE TITLE
Failed to scrape resource collection 'Application-insight-landscape' - resource discovery group

### ISSUE THREAD

**Issue by mgLearningAccount2** [tomkerkhove/promitor#2067] opened 2022-07-01 05:16 UTC
### Discussed in https://github.com/tomkerkhove/promitor/discussions/2066

<div type='discussions-op-text'>

<sup>Originally posted by **mgLearningAccount2** June 30, 2022</sup>
I have made a simple configuration setup with Prometheus -- Promitor -- Azure AppInsight , these config are done locally without any assist from kubernetes. 

Setup Details:
--------------
docker run command:
docker run -d -p 8999:80 --name promitor-agent-scraper --env AUTH_APPKEY=xxxxxx-xxxx-xxxx-xxxxxx --volume c:/promitor/metrics-declaration.yaml:/config/metrics-declaration.yaml --volume c:/promitor/runtime.yaml:/config/runtime.yaml ghcr.io/tomkerkhove/promitor-agent-scraper:2.6.0

![image](https://user-images.githubusercontent.com/106647650/176686786-d4d230ad-cd9f-4e80-bcaa-0f91f01e3e6b.png)

![image](https://user-images.githubusercontent.com/106647650/176687015-ecd12495-51cc-493c-8d85-aaf622deae06.png)

![image](https://user-images.githubusercontent.com/106647650/176687097-60856ee6-e600-4ea3-b828-52087cc5e242.png)

![image](https://user-images.githubusercontent.com/106647650/176734240-6430ee5d-06c9-41a8-9fc5-eef833ab7c50.png)

Currently my Promitor docker is running successfully and their localhost/metric endpoint are available Prometheus target. But, I am facing few issues between Promitor and azure configuration. 

1. how to expose an appinsight data metric to metric-declaration.yml? I have updated the metric.yml file with azure appinsight resources is this the resource group we have to refer? and does the metric only available when data is present? 

![image](https://user-images.githubusercontent.com/106647650/176733974-a498969e-9106-489f-931e-1ec7cf5616ba.png)

And in the AzureMetricConfiguration should I be using namespace or the metric value from AppInSight.
![image](https://user-images.githubusercontent.com/106647650/176733777-77579f79-0319-4aed-98c8-eb5b29c33410.png)

2. The another issue I was facing is the "resource discovery group", based on [doc](https://docs.promitor.io/v2.6/how-it-works/#scraping-azure-monitor-metrics) Promitor discovery agent query the data from azure resource graph. Even thought these config are mentioned as optional, I am getting error on this when the container is running. Is this to be ignored or if left will it affect data scrapping.

![image](https://user-images.githubusercontent.com/106647650/176806182-8729b79c-0aa8-4cf1-bc92-1bb98ce5dcc0.png)
![image](https://user-images.githubusercontent.com/106647650/176689350-08771b01-a9d1-470e-8306-afb2d44ef413.png)

4. In runtime.yaml configuring the Authentication part for mode & indentityId (where these value are taken from exactly), is this required and under which condition to be included? 
error when running the container
![image](https://user-images.githubusercontent.com/106647650/176731535-0448c11c-f78a-455b-b431-d8a9b8a5b1a8.png)

</div>

**Comment by tomkerkhove** [comment] 2022-07-01 09:27
Closing as this is a duplicate of https://github.com/tomkerkhove/promitor/discussions/2066

**Closed by tomkerkhove** 2022-07-01 09:27 UTC

**Comment by mgLearningAccount2** [comment] 2022-07-06 12:30
I have made few changes to metric declaration file and facing following issues. These configuration are done locally without any use of AKS.
For the Auth mode: service provide (App registration) have read access on the AppInsight resource. 
version: 2.7.0

Issue 1:
--------
![image](https://user-images.githubusercontent.com/106647650/177546714-d7c4d57f-f139-4d57-bc34-76c2d152e359.png)

Issue 2:
--------
![image](https://user-images.githubusercontent.com/106647650/177547186-09491854-52c6-4d9a-9541-6bd1c521c2d6.png)
