### ISSUE TITLE
Unable to add https://charts.promitor.io

### ISSUE THREAD

**Issue by Takshika** [tomkerkhove/promitor#1752] opened 2021-09-01 12:55 UTC
### Discussed in https://github.com/tomkerkhove/promitor/discussions/1751

<div type='discussions-op-text'>

<sup>Originally posted by **Takshika** September  1, 2021</sup>
I am not able to add promitor repo. It throws errors - "Error: looks like "https://charts.promitor.io/" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile"

Followed https://artifacthub.io/packages/helm/promitor/promitor-agent-scraper to add promitor repo. Can someone help me understand if I am taking some wrong path and what would be correct path.

➜  helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
➜  helm repo add promitor https://charts.promitor.io/
helm repo add promitor https://charts.promitor.io/
Error: looks like "https://charts.promitor.io/" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile</div>

**Comment by tomkerkhove** [comment] 2021-09-01 13:18
Duplicate of #1751

**Closed by tomkerkhove** 2021-09-01 13:18 UTC
